name: Build Container
description: >-
  Build and test a container using the standard llvm naming scheme for containers.

inputs:
  tag:
    description: >-
      The tag to use for this container.
    required: false
  container-name:
    description: >-
      The name for the container. 
    required: true
  dockerfile:
    description: >-
      Path to docker file.
    required: false
  target:
    description: >-
      The container target to build 'passed to podman via ---target option'
    required: false
  context:
    description: >-
      Path to context for the container build.
    required: false
  test-command:
    description: >-
      Test command to run to ensure the container is working correctly.
    required: false
      
outputs:
  name:
    description: "FOO"
    value: ${{ steps.id.outputs.name }}

runs:
  using: "composite"
  steps:
    # podman is not installed by default on the ARM64 images.
    - name: Install Podman
      if: runner.arch == 'ARM64'
      run: |
        sudo apt-get install podman

