name: Get Job ID
inputs:
  job-name:
    required: false
    type: 'string'

outputs:
  job-id:
    description: "A space delimited list of check-targets to pass to ninja."
    value: ${{ steps.job-id.outputs.result }}

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
      id: job-id
      with:
        script: |
          const job_data = await github.rest.actions.listJobsForWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          });

          for (job of job_data.data.jobs) {
            console.log(job)
            if (job.name == "${{ inputs.job-name }}") {
              return job.id
            }
          }
