name: PR sccache restore

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
      id: artifact-url
      with:
        script: |
          const data = await github.rest.actions.listArtifactsForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'sccache-pr' + context.issue.number
          })

          console.log(data.data.artifacts)

          for (artifact of data.data.artifacts) {
            if (artifact.expired) {
              continue;
            }
            console.log(artifact)
            const url = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: "zip"
            })
            console.log(url.url)
            return url.url
          }
          console.log("Could not find previous sccache for this PR.")

    - shell: bash
      if: steps.artifact-url.outputs.result != ''
      run: |
        curl -L -o sccache-pr${{ github.event.number }}.zip ${{ steps.artifact-url.outputs.result }}
        # Is this the best way to clear the cache?
        rm -Rf .sccache/
        unzip -d .sccache sccache-pr${{ github.event.number}}.zip
        ls -ltr


