name: PR sccache restore

runs:
  using: "composite"
  steps:
    - uses: ./.github/workflows/unprivileged-download-artifact
      id: download-artifact
      with:
        run-id: ${{ github.event.workflow_run.id }}
        artifact-name: sccache-pr${{ github.event.issue.number }}

    - shell: bash
      if: steps.download-artifact.outputs.filename != ''
      run: |
        # Is this the best way to clear the cache?
        rm -Rf .sccache/
        unzip ${{ steps.download-artifact.outputs.filename }}
