name: Require Release Manager
description: >-
  This checks to make sure the person that initiated the workflow is a
  release manager.
inputs:
  LLVM_TOKEN_GENERATOR_CLIENT_ID:
    description: >-
      Client ID for generating access tokens.
    required: true
  LLVM_TOKEN_GENERATOR_PRIVATE_KEY:
    description: >-
      Private key for generating access tokens
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Permissions
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        github-token: ${{ inputs.LLVM_TOKEN_GENERATOR_PRIVATE_KEY }}
        script: |
          const response = await github.rest.teams.getMembershipForUserInOrg({
             org: context.repo.owner,
             team_slug: "llvm-release-managers",
             username: "tstellar"
          });
          console.log(response)
    - name: Check Permissions 2
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        github-token: ${{ inputs.LLVM_TOKEN_GENERATOR_PRIVATE_KEY }}
        script: |
          const response = await github.rest.teams.getMembershipForUserInOrg({
             org: context.repo.owner,
             team_slug: "llvm-release-managers",
             username: "nikic"
          });
          console.log(response)
