name: Build CI Tooling Containers

permissions:
  contents: read

on:
  push:
    paths:
      - .github/workflows/build-ci-container-tooling.yml
      - '.github/workflows/containers/github-action-ci-tooling/**'
      - llvm/utils/git/requirements_formatting.txt
      - llvm/utils/git/requirements_linting.txt
  pull_request:
    paths:
      - .github/workflows/build-ci-container-tooling.yml
      - '.github/workflows/containers/github-action-ci-tooling/**'
      - llvm/utils/git/requirements_formatting.txt
      - llvm/utils/git/requirements_linting.txt

jobs:
  build-ci-container-tooling:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - container-name: code-format
            test-command: 'cd $HOME && clang-format --version | grep version && git-clang-format -h | grep usage && black --version | grep black'
          - container-name: code-lint
            test-command: 'cd $HOME && clang-tidy --version | grep version && clang-tidy-diff.py -h | grep usage'
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: |
            .github/workflows/containers/github-action-ci-tooling/
            llvm/utils/git/requirements_formatting.txt
            llvm/utils/git/requirements_linting.txt
            clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py

      - name: Build Container
        uses: ./.github/workflows/build-container
        with:
          container-name: ci-ubuntu-24.04-${{ matrix.container-name }}
          dockerfile: github/workflows/containers/github-action-ci-tooling/Dockerfile
          target: ci-container-${{ matrix.container-name }}
          test-command: ${{ matrix.test-command }}
        
  push-ci-container:
    if: github.event_name == 'push'
    needs:
      - build-ci-container-tooling
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download container
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0

      - name: Push Container
        run: |
          function push_container {
            image_name=$1
            latest_name=$(echo $image_name | sed 's/:[a-f0-9]\+$/:latest/g')
            podman tag $image_name $latest_name
            echo "Pushing $image_name ..."
            podman push $image_name
            echo "Pushing $latest_name ..."
            podman push $latest_name
          }

          podman login -u ${{ github.actor }} -p $GITHUB_TOKEN ghcr.io
          for f in $(find . -iname '*.tar'); do
            image_name=$(podman load -q -i $f | sed 's/Loaded image: //g')
            push_container $image_name

            if echo $image_name | grep '/amd64/'; then
              # For amd64, create an alias with the arch component removed.
              # This matches the convention used on dockerhub.
              default_image_name=$(echo $(dirname $(dirname $image_name))/$(basename $image_name))
              podman tag $image_name $default_image_name
              push_container $default_image_name
            fi
          done
