name: CCache test

permissions:
  contents: read

on:
  push:

jobs:
  ccache-test:
    runs-on: macos-13
    steps:
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          # A full build of llvm, clang, lld, and lldb takes about 250MB
          # of ccache space. There's not much reason to have more than this,
          # because we usually won't need to save cache entries from older
          # builds.  Also, there is an overall 10GB cache limit, and each
          # run creates a new cache entry so we want to ensure that we have
          # enough cache space for all the tests to run at once and still
          # fit under the 10 GB limit.
          max-size: 500M
          key: ${{ matrix.os }}-ccache-test
          variant: sccache

      - name: Test ccache
        run: |
          echo "int main(){}" > test.c
          SCCACHE_DEBUG=verbose sccache clang test.c
          sccache -s
        
