name: CPU check

on:
  push:


jobs:
  cpu-check:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - run: nproc
        shell: bash
