name: Disk Space

permissions:
  contents: read

on:
  push:

jobs:
  disk-space-container:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Check Disk Space
        run: |
          df -h
          pwd
           
  disk-space-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Check Disk Space
        run: |
          df -h
          pwd
          du -h --max-depth=2 / 2>/dev/null | sort -h
          du -h --max-depth=2 /usr/local /opt/ 2>/dev/null | sort -h

      - name: Remove some largefiles
        run: |
          sudo apt-get update
          sudo apt-get remove php
          df -h
          #dpkg -S /usr/local/.ghcub
          #dpkg -S /usr/local/lib/android
          dpkg --get-selections



