name: Issue Subscriber

on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  auto-subscribe:
    environment:
      name: main-branch-only
      deployment: false
    runs-on: ubuntu-24.04
    container:
      image: 'ghcr.io/tstellar/ci-ubuntu-24.04-github-automation:latest'
    steps:
      - id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3  # v3.1.1
        if: false
        with:
          client-id: ${{ secrets.LLVM_TOKEN_GENERATOR_CLIENT_ID }}
          private-key: ${{ secrets.LLVM_TOKEN_GENERATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-members: read
          permission-contents: read
          permission-issues: write

      - name: Update watchers
        env:
          LABEL_NAME: ${{ github.event.label.name }}
          ISSUE_SUBSCRIBER_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          github-automation.py \
            --token "$ISSUE_SUBSCRIBER_TOKEN" \
            issue-subscriber \
            --issue-number '${{ github.event.issue.number }}' \
            --label-name "$LABEL_NAME"
