name: CI

on:
  push:
    types:

env:
  # -j1 There appears to be a race condition that causes
  # llvm/test/ThinLTO/X86/cache.ll to fail on MacOS.  Disabling threads in
  # lit fixes this.
  LIT_OPTS: -j1
jobs:
  build_llvm:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        crlf:
          - true
          - false
    steps:
    - name: Dump git config
      run: git config -l
    - name: set crlf settings
      run: git config --global core.autocrlf=${{ matrix.crlf }}
    - name: Dump git config
      run: git config -l
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Ninja
      uses: tstellar/actions/install-ninja@master
      with:
        os: ${{ runner.os }}
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: tstellar/actions/setup-windows@master
      with:
        arch: amd64
    - name: Create build directory
      run: | 
         mkdir build
         cd build
         pwd
    - name: Configure llvm
      uses: tstellar/actions/configure-llvm-project@master
      with:
        cmake_args: -G Ninja -DCMAKE_BUILD_TYPE=Release ../llvm-project/llvm -DLLVM_TARGETS_TO_BUILD=X86
        os: ${{ runner.os }}
    - name: Build llvm
      run: ninja check-all
    - name: Run Test
      if: failure()
      run: ./bin/llvm-lit -vva  test/MC/ARM/preserve-comments-arm.s
    - name: Upload Files
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: file1
        path: build/test/MC/ARM/Output/preserve-comments-arm.s.tmp
    - name: Upload Files
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: file2
        path: build/test/MC/ARM/Output/preserve-comments-arm.s.tmp2
