name: PR Subscriber

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read

jobs:
  auto-subscribe:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Automation Script
        run: |
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
          curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/requirements.txt
          chmod a+x github-automation.py
          pip install -r requirements.txt

      - name: Update watchers
        run: |
          ./github-automation.py \
          --token '${{ secrets.ISSUE_SUBSCRIBER_TOKEN }}' \
          pr-subscriber \
          --issue-number '${{ github.event.pull_request.number }}'
