name: "Windows Precommit Tests"

permissions:
  contents: read
  actions: write

on:
  pull_request:
    branches:
      - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  compute-projects:
    name: "Compute Projects to Test"
    runs-on: ubuntu-22.04
    outputs:
      projects: ${{ steps.vars.outputs.projects }}
      check-targets: ${{ steps.vars.outputs.check-targets }}
      test-build: ${{ steps.vars.outputs.check-targets != '' }}
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Compute projects to test
        id: vars
        uses: ./.github/workflows/compute-projects-to-test

  build-windows:
    name: "Build"
    runs-on: windows-2022
    outputs:
      build-timeout: ${{ steps.build.outputs.timeout }}
      build-failed: ${{ steps.build.outputs.failed }}
    needs:
      - compute-projects
    if: ${{ needs.compute-projects.outputs.test-build == 'true' }}
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          pattern: timeout
          merge-multiple: true

      - name: Unpack Artifact
        id: timeout-artifact
        shell: bash
        run: |
          if [ -e llvm-project.tar.zst ]; then
            tar --zstd -xf llvm-project.tar.zst
            rm llvm-project.tar.zst
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Windows
        uses: llvm/actions/setup-windows@main
        with:
          arch: amd64

      - name: Fetch LLVM sources
        uses: actions/checkout@v4
        if: ${{ steps.timeout-artifact.outputs.exists != 'true' }}  

      - name: Setup sccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 2G
          variant: sccache
          key: precommit-windows
      
      - name: Restore sccache from previous PR run
        uses: ./.github/workflows/pr-sccache-restore

      - name: Configure
        shell: bash
        run: |
          cmake -B build -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="${{ needs.compute-projects.outputs.projects }}" \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_LIT_ARGS="-v --no-progress-bar" \
            -DCMAKE_C_COMPILER_LAUNCHER=sccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache \
            -S llvm

      - name: Build
        shell: bash
        id: build
        timeout-minutes: 330
        run: |
          ninja -C build ${{ needs.compute-projects.outputs.check-targets }} && pass=1
          echo "completed=true" >> $GITHUB_OUTPUT
          [ $pass ] || false

      - name: Save sccache for next PR run
        if: always()
        uses: ./.github/workflows/pr-sccache-save

      - name: Package Build Directory
        shell: bash
        if: always() && steps.build.outputs.completed != 'true'
        run: |
          tar -c . | zstd -T0 -c > ../llvm-project.tar.zst
          mv ../llvm-project.tar.zst .

      - name: Upload Build
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
        if: always() && steps.build.outputs.completed != 'true'
        with:
          name: timeout
          path: llvm-project.tar.zst
          retention-days: 2
