name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean

  workflow_call:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean

permissions:
  contents: read # Default everything to read-only

jobs:
  prepare:
    name: Prepare to build binaries
    runs-on: ubuntu-22.04
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      release: ${{ steps.vars.outputs.release }}
      build-dir: ${{ steps.vars.outputs.build-dir }}
      rc-flags: ${{ steps.vars.outputs.rc-flags }}
      ref: ${{ steps.vars.outputs.ref }}
      upload: ${{ steps.vars.outputs.upload }}

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@v4

    - name: Check Permissions
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        ./llvm/utils/release/./github-upload-release.py --token "$GITHUB_TOKEN" --user ${{ github.actor }} check-permissions || true

    - name: Collect Variables
      id: vars
      # In order for the test-release.sh script to run correctly, the LLVM
      # source needs to be at the following location relative to the build dir:
      # | X.Y.Z-rcN | ./rcN/llvm-project
      # | X.Y.Z     | ./final/llvm-project
      #
      # We also need to set divergent flags based on the release version:
      # | X.Y.Z-rcN | -rc N -test-asserts
      # | X.Y.Z     | -final
      run: |
        if [ -n "${{ inputs.upload }}" ]; then
          upload="${{ inputs.upload }}"
        else
          upload="false"
        fi
        bash .github/workflows/set-release-binary-outputs.sh "${{ inputs.release-version }}" "$upload"

  build-binaries:
    name: ${{ matrix.target.triple }}
    permissions:
      contents: write # To upload assets to release.
    needs: prepare
    runs-on: ${{ matrix.target.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - triple: x86_64-linux-gnu-ubuntu-22.04
            runs-on: ubuntu-22.04-16x64
            debian-build-deps: >
              chrpath
              gcc-multilib
              ninja-build

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@v4
      with:
        ref: ${{ needs.prepare.outputs.ref }}
        path: ${{ needs.prepare.outputs.build-dir }}/llvm-project

    - name: Install Brew build dependencies
      if: matrix.target.brew-build-deps != ''
      run: brew install ${{ matrix.target.brew-build-deps }}

    - name: Install Debian build dependencies
      if: matrix.target.debian-build-deps != ''
      run: sudo apt install ${{ matrix.target.debian-build-deps }}

    - name: Set macOS build env variables
      if: runner.os == 'macOS'
      run: |
        echo "MACOSX_DEPLOYMENT_TARGET=10.9" >> "$GITHUB_ENV"

    - name: Build and test release
      run: |
        ${{ needs.prepare.outputs.build-dir }}/llvm-project/llvm/utils/release/test-release.sh \
        -release ${{ needs.prepare.outputs.release }} \
        ${{ needs.prepare.outputs.rc-flags }} \
        -triple ${{ matrix.target.triple }} \
        -use-ninja \
        -no-checkout \
        -no-test-suite

    - name: Upload binaries
      if: ${{ always() && needs.prepare.outputs.upload == 'true' }}
      run: |
        sudo apt install python3-github
        ${{ needs.prepare.outputs.build-dir }}/llvm-project/llvm/utils/release/github-upload-release.py \
        --token ${{ github.token }} \
        --release ${{ needs.prepare.outputs.release-version }} \
        upload \
        --files ${{ needs.prepare.outputs.build-dir }}/clang+llvm-${{ needs.prepare.outputs.release-version }}-${{ matrix.target.triple }}.tar.xz
