name: Release Doxygen

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload documentation'
        required: false
        type: boolean

  workflow_call:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload documentation'
        required: false
        type: boolean

jobs:
  release-doxygen:
    name: Build and Upload Release Doxygen
    runs-on: ubuntu-latest
    env:
      upload: ${{ inputs.upload && !contains(inputs.release-version, 'rc') }}
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pwd
          ls
          sudo apt-get update
          sudo apt-get install -y \
              doxygen \
              graphviz \
              python3-github \
              ninja-build \
              texlive-font-utils
          pip3 install --user -r ./llvm/docs/requirements.txt
          echo "UPLOAD SETTING: $upload"

      - name: Build Doxygen
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./llvm/utils/release/build-docs.sh -release "${{ inputs.release-version }}" -no-sphinx

      - name: Upload Doxygen
        if: env.upload
        run: |
          ./llvm/utils/release/github-upload-release.py --token "$GITHUB_TOKEN" --release "${{ inputs.release-version }}" --user "${{ github.actor }}" upload --files ./*doxygen*.tar.xz
