name: Release Task

permissions:
  contents: read

on:
  push:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
      - 'pypi-test-*'

jobs:
  release-lit:
    name: Release Lit
    needs: validate-tag
    uses: ./.github/workflows/release-lit.yml
    with:
      release-version: 21.1.0
