name: Release Documentation

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload documentation'
        required: false
        type: boolean

  workflow_call:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload documentation'
        required: false
        type: boolean

jobs:
  release-documentation:
    name: Build and Upload Release Documentation
    runs-on: ubuntu-latest
    env:
      upload: ${{ inputs.upload && !contains(inputs.release-version, 'rc' }}
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              doxygen \
              graphviz \
              python3-github \
              ninja-build \
              texlive-font-utils
          pip3 install --user -r ./llvm/docs/requirements.txt
          echo "UPLOAD SETTING: $upload"

      - name: Checkout LLVM
        uses: actions/checkout@v4
        with:
          ref: "llvmorg-${{ inputs.release-version }}"

      - name: Build Documentation
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./llvm/utils/release/build-docs.sh -release "${{ inputs.release-version }}"
          ./llvm/utils/release/github-upload-release.py --token "$GITHUB_TOKEN" --release "${{ inputs.release-version }}" --user "${{ github.actor }}" upload --files ./*doxygen*.tar.xz

      - name: Create Release Notes Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-notes
          path: docs-build/html-export/

      - name: Clone www-releases
        if: env.upload
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/www-releases
          ref: main
          fetch-depth: 0
          path: www-releases

      - name: Upload Release Notes
        if: env.upload
        env:
          WWW_RELEASES_TOKEN: ${{ secrets.WWW_RELEASES_TOKEN }}
        run: |
          mkdir -p ../www-releases/${{ inputs.release-version }}
          mv ./docs-build/html-export/* ../www-releases/${{ inputs.release-version }}
          cd ../www-releases
          git add ${{ inputs.release-version }}
          git config user.email "llvmbot@llvm.org"
          git config user.name "llvmbot"
          git commit -a -m "Add ${{ inputs.release-version }} documentation"
          git push "https://$WWW_RELEASES_TOKEN@github.com/${{ github.repository_owner }}/www-releases" main:main
    
