name: Release Binaries

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean

  workflow_call:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload binaries to the release page'
        required: true
        default: false
        type: boolean
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 8 1 * *'

permissions:
  contents: read # Default everything to read-only

jobs:
  prepare:
    name: Prepare to build binaries
    runs-on: ubuntu-22.04
    outputs:
      release-version: ${{ steps.vars.outputs.release-version }}
      flags: ${{ steps.vars.outputs.flags }}
      build-dir: ${{ steps.vars.outputs.build-dir }}
      rc-flags: ${{ steps.vars.outputs.rc-flags }}
      ref: ${{ steps.vars.outputs.ref }}
      upload: ${{ steps.vars.outputs.upload }}

    steps:
    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Install Dependencies
      run: |
        pip install -r ./llvm/utils/git/requirements.txt
        df -h

    - name: Collect Variables
      id: vars
      # In order for the test-release.sh script to run correctly, the LLVM
      # source needs to be at the following location relative to the build dir:
      # | X.Y.Z-rcN | ./rcN/llvm-project
      # | X.Y.Z     | ./final/llvm-project
      #
      # We also need to set divergent flags based on the release version:
      # | X.Y.Z-rcN | -rc N -test-asserts
      # | X.Y.Z     | -final
      run: |
        tag="${{ github.ref_name }}"
        trimmed=$(echo ${{ inputs.release-version }} | xargs)
        [[ "$trimmed" != "" ]] && tag="llvmorg-$trimmed"
        if [ "$tag" = "main" ]; then
          # If tag is main, then we've been triggered by a scheduled so pass so
          # use the head commit as the tag.
          tag=`git rev-parse HEAD`
        fi
        if [ -n "${{ inputs.upload }}" ]; then
          upload="${{ inputs.upload }}"
        else
          upload="false"
        fi
        bash .github/workflows/set-release-binary-outputs.sh "$tag" "$upload"

  build-stage1:
    name: "Build Stage 1 ${{ matrix.os }}"
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
    steps:
    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: ${{ needs.prepare.outputs.ref }}

    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
      with:
        max-size: 250M
        key: sccache-${{ matrix.os }}-release
        variant: sccache

    - name: Build Stage 1 Clang
      run: |
        mkdir -p /mnt/build
        ls -ltr /mnt/build
        cmake -G Ninja -C clang/cmake/caches/Release.cmake -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache -DCMAKE_POSITION_INDEPENDENT_CODE=ON -S llvm -B /mnt/build
        ninja -v -C /mnt/build

    # We need to create an archive of the build directory, because it has too
    # many files to upload.
    - name: Save Build and Source Directory
      run: |
        tar -czf ${{ github.workspace }}/../llvm-project.tar.gz .
        mv ../llvm-project.tar.gz ${{ github.workspace }}
        tar -czf ${{ github.workspace }}/build.tar.gz /mnt/build

    - name: Upload Stage 1 Source
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage1-source
        path: ${{ github.workspace }}/llvm-project.tar.gz
    
    - name: Upload Stage 1 Build Dir
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage1-build
        path: ${{ github.workspace }}/bulid.tar.gz

  build-stage2:
    name: "Build Stage 2 ${{ matrix.os }}"
    needs:
      - prepare
      - build-stage1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: Download Stage 1 Artifacts
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: stage1-*
        merge-multiple: true

    - name: Unpack Artifact
      run: |
        tar -xzf llvm-project.tar.gz 
        rm llvm-project.tar.gz
        tar -C /mnt -xzf build.tar.gz
        rm build.tar.gz
        ls -l /mnt

    - name: Build Stage 2
      run: |
        ninja -C /mnt/build stage2-instrumented

    # We need to create an archive of the build directory, because it has too
    # many files to upload.
    - name: Save Build and Source Directory
      run: |
        tar -czf ${{ github.workspace }}/../llvm-project.tar.gz .
        mv ../llvm-project.tar.gz ${{ github.workspace }}
        tar -czf  ${{ github.workspace }}/build.tar.gz /mnt/build/
    
    - name: Upload Stage 2 Source
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage2-source
        path: ${{ github.workspace }}/llvm-project.tar.gz
    
    - name: Upload Stage 2 Build Dir
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage2-build
        path: ${{ github.workspace }}/build.tar.gz


  build-stage3:
    name: "Build Stage 3 ${{ matrix.os }}"
    needs:
      - prepare
      - build-stage2
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: 'Download artifact'
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: stage2-*
        merge-multiple: true

    - name: Unpack Artifact
      run: |
        tar -xzf llvm-project.tar.gz 
        rm llvm-project.tar.gz
        tar -C /mnt -xzf build.tar.gz
        rm build.tar.gz

    - name: Build Release Package
      run: |
        ninja -C /mnt/build stage2-package
    
    - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      if: always()
      with:
        name: LLVM-${{ matrix.target.release-version }}-Linux.tar.gz
        path: /mnt/build/LLVM-${{ matrix.target.release-version }}-Linux.tar.gz

    # We need to create an archive of the build directory, because it has too
    # many files to upload.
    - name: Save Build and Source Directory
      run: |
        tar -czf ${{ github.workspace }}/../llvm-project.tar.gz .
        mv ../llvm-project.tar.gz ${{ github.workspace }}
        tar -czf ${{ github.workspace }}/build.tar.gz /mnt/build
    
    - name: Upload Stage 3 Source
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage3-source
        path: ${{ github.workspace }}/llvm-project.tar.gz
    
    - name: Upload Stage 3 Buidl Dir
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      with:
        name: stage3-build
        path: ${{ github.workspace }}/build.tar.gz

  test-stage2:
    name: "Test Stage 3"
    needs:
      - prepare
      - build-stage3
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@22e9f909d35b50bd1181709564bfe816eaeaae81 # main

    - name: 'Download artifact'
      uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
      with:
        name: stage3-*
        merge-multiple: true

    - name: Unpack Artifact
      run: |
        tar -xzf llvm-project.tar.gz 
        rm llvm-project.tar.gz
        tar -C /mnt -xzf build.tar.gz
        rm build.tar.gz
    
    - name: Run Tests
      run: |
        ninja -C /mnt/build stage2-check-all

  build-binaries-windows:
    if: github.repository == 'llvm/llvm-project'
    name: Windows ${{ matrix.target.variant }} Release Build
    permissions:
      contents: write # To upload assets to the release
    needs:
      - prepare  
    runs-on: ${{ matrix.target.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - variant: x64
            runs-on: windows-2019
            file-suffix: -win64
            build-dir: build64
          - variant: x86
            runs-on: windows-2019
            file-suffix: -win32
            build-dir: build32
    steps:
    - name: Checkout LLVM
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        ref: main
        path: ${{ needs.prepare.outputs.build-dir }}/llvm-project

    - name: Setup sccache
      uses: hendrikmuhs/ccache-action@ca3acd2731eef11f1572ccb126356c2f9298d35e # v1.2.9
      with:
        max-size: 250M
        key: sccache-${{ matrix.target.os }}-release
        save: false
        variant: sccache
      
    - name: Setup Windows
      if: startsWith(matrix.os, 'windows')
      uses: llvm/actions/setup-windows@main
      with:
        arch: amd64
    
    - name: Build and test release
      shell: cmd
      run: |
        dir
        dir ${{ needs.prepare.outputs.build-dir }}\llvm-project\llvm\utils\release\
        ${{ needs.prepare.outputs.build-dir }}\llvm-project\llvm\utils\release\build_llvm_release.bat --${{ matrix.target.variant }} --version=${{ needs.prepare.outputs.release-version }} --local-python

    - uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 #v4.3.0
      if: always()
      with:
        name: LLVM-${{ matrix.target.release-version }}-${{ matrix.target.file-suffix }}.exe
        path: ${{ needs.prepare.outputs.build-dir }}\llvm-project\llvm_package_${{ needs.prepare.outputs.release-version }}\${{ matrix.target.build-dir }}\LLVM-${{ needs.prepare.outputs.release-version }}-${{ matrix.target.file-suffix }}.exe
