name: Release Documentation

permissions:
  contents: read

on:
  push:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release Version'
        required: true
        type: string
      upload:
        description: 'Upload documentation'
        required: false
        type: boolean

  workflow_call:
    secrets:
      LLVMBOT_WWW_RELEASES_PUSH:
        description: "Secret used to push changes to llvmbot www-releases fork."
        required: false
      WWW_RELEASES_TOKEN:
        description: "Secret used to create a PR with the documentation changes."
        required: false

jobs:
  release-documentation:
    name: Build and Upload Release Documentation
    environment: release
    runs-on: ubuntu-24.04
    env:
      upload: ${{ inputs.upload && !contains(inputs.release-version, 'rc') }}
    steps:
      - run: |
          # abc
          echo ${{ secrets.LLVMBOT_WWW_RELEASES_PUSH }} | wc -m
          # abcdef
          echo ${{ secrets.WWW_RELEASES_TOKEN }} | wc -m
