name: Release Task

permissions:
  contents: read

on:
  push:
    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
      - 'llvmorg-*'

jobs:
  release-documentation:
    name: Build and Upload Release Documentation
    uses: ./.github/workflows/release-documentation.yml
