name: Release Task

on:
  push:
    tags:
      # The regex support here is limited, so just match everything that starts with llvmorg- and filter later.
      - 'llvmorg-*'

jobs:
  release-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Validate Tag
      id: validate-tag
      run: |
        test "${{ github.actor }}" = "tstellar"
        echo "${{ github.ref }}" | grep -e 'llvmorg-[0-9.]\+\(-rc[0-9]\+\)\?'$
        release_version=`echo "${{ github.ref }}" | sed 's/refs\/tags\/llvmorg-//g'`
        echo "::set-output name=release-version::$release_version"

    - name: Install Dependencies
      run: |
        sudo apt-get install doxygen python3-sphinx python3-recommonmark ninja-build graphviz texlive-font-utils python3-github
        pip3 install --user sphinx-markdown-tables

    - name: Checkout LLVM
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
      
    - name: Create Release
      run: |
         echo "./llvm/utils/release/./github-upload-release.py --token ${{ github.token }} --release ${{ steps.validate-tag.outputs.release-version }} create"
      
    - name: Build Documentation
      run: |
        bash llvm/utils/release/build-docs.sh -srcdir llvm -release ${{ steps.validate-tag.outputs.release-version }}
        echo "./llvm/utils/release/./github-upload-release.py --token ${{ github.token }} --release ${{ steps.validate-tag.outputs.release-version }} upload --files *doxygen*.tar.xz"
        ls *doxygen*.tar.xz

    - name: Clone www-releases
      if: ! contains(${{ steps.validate-tag.outputs.release-version }}, 'rc')
      uses: actions/checkout@v1
      with:
        repository: https://github.com/tstellar/www-releases
        ref: main
        fetch-depth: 0
        path: www-releases
    
    - name: Upload Release Notes
      if: ! contains(${{ steps.validate-tag.outputs.release-version }}, 'rc')
      run: |
        mkdir -p www-release/${{ steps.validate-tag.outputs.release-version }}
        mv ./docs-build/html-export/* www-releases/${{ steps.validate-tag.outputs.release-version }}
        git -C www-releases add www-releases/${{ steps.validate-tag.outputs.release-version }}
        git -C push origin main:main

