name: Test Python

on:
  push:



permissions:
  contents: read # Default everything to read-only

jobs:
  test-python:
    runs-on: macos-14
    steps:
      - shell: bash
        run: |
          pip install pygithub
          python3 -c 'import github'
