name: Test
on:
  push:


jobs:
  test-require-release-manager:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: .github/workflows/
      - name: Test
        uses: ./.github/workflows/require-release-manager
        with:
          LLVM_TOKEN_GENERATOR_CLIENT_ID: ${{ secrets.RELEASE_TASKS_USER_TOKEN }}
          LLVM_TOKEN_GENERATOR_PRIVATE_KEY: ${{ secrets.RELEASE_TASKS_USER_TOKEN }}
