name: Test Bolt

permissions:
  contents: read

on: push


jobs:
  test-bolt:
    name: Test Bolt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: llvm/actions/install-ninja@main
      - run: |
          cmake -G Ninja -S llvm -B bolt-build -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;lld;bolt"  -DLLVM_LIT_ARGS="-vv" -DLLVM_TARGETS_TO_BUILD=Native -DBOLT_INCLUDE_TESTS=ON
          ninja -C bolt-build check-bolt
